<p><a href="<?php echo $this->url(
    array(
        'controller' => 'pacienti',
        'action'     => 'index',
    	'module' => 'default'
    ),
    'default',
    true) ?>">Test pacienti</a></p>

Pacienti: <br />
<dl>
    <?php foreach ($this->entries as $entry): ?>
    <dt><?php echo $this->escape($entry->nume_pacient) ?></dt>
    <dd><?php echo $this->escape($entry->prenume_pacient) ?></dd>
    <?php endforeach ?>
</dl>